package kartoyunu;

import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aybuk
 */
public class oyuncukartlari extends javax.swing.JFrame {

    /**
     * Creates new form oyuncukartlari
     */
    test o = new test();
    oyuncu bilgisayaro = null;
    oyuncu kullanicio = null;
    int bilgisayarSectigiKart;
    int kullaniciSectigiKart;
    int pcOynadiMi;
    int kOynadiMi;
    String oyuncu2tip;
    boolean kartsecimi = true;
    int sayac = 0;
    int sayac1 = 0;
    int sonkart = 0;

    public oyuncukartlari() {
        initComponents();
        this.setLocation(0, 0);  // Görünüm olarak açılan pencerenin ekranın tam ortasında çıkması için
        this.setSize(1920, 1080);
        o.oyuncuolustur();
        o.oyuncufKartOlustur();
        o.oyuncubKartOlustur();
        int tür = 1;

        if (tür == 1) {
            bilgisayaro = new bilgisayar(1, "Bilgisayar", 0);
            kullanicio = new kullanici(2, "Kullanıcı", 0);

        }

        oyuncu2tip = String.valueOf(kullanicio.getClass());

        o.futbolkartAta(kullanicio);

        o.basketbolkartAta(kullanicio);

        o.futbolkartAtab(bilgisayaro);

        o.basketbolkartAtab(bilgisayaro);

        deste.setIcon(o.oyuncuImagesf.get(8));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pc2kart2 = new javax.swing.JLabel();
        pc2kart3 = new javax.swing.JLabel();
        pc2kart4 = new javax.swing.JLabel();
        pc2kart5 = new javax.swing.JLabel();
        pc2kart6 = new javax.swing.JLabel();
        pc2kart7 = new javax.swing.JLabel();
        pc2kart8 = new javax.swing.JLabel();
        kullanici1kart1 = new javax.swing.JLabel();
        kullanici1kart2 = new javax.swing.JLabel();
        kullanici1kart3 = new javax.swing.JLabel();
        kullanici1kart4 = new javax.swing.JLabel();
        kullanici1kart5 = new javax.swing.JLabel();
        kullanici1kart6 = new javax.swing.JLabel();
        kullanici1kart7 = new javax.swing.JLabel();
        kullanici1kart8 = new javax.swing.JLabel();
        pc2kart1 = new javax.swing.JLabel();
        ortakart1 = new javax.swing.JLabel();
        kartlariAc = new javax.swing.JButton();
        kartAc = new javax.swing.JButton();
        kartlarıAco = new javax.swing.JButton();
        ortakart2 = new javax.swing.JLabel();
        kartAt = new javax.swing.JButton();
        oyuncupuan = new javax.swing.JLabel();
        bilgisayarpuan = new javax.swing.JLabel();
        karsilastirmatur = new javax.swing.JLabel();
        deste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pc2kart2.setText("p1k2");

        pc2kart3.setText("p1k3");

        pc2kart4.setText("p1k4");

        pc2kart5.setText("p1k5");

        pc2kart6.setText("p1k6");

        pc2kart7.setText("p1k7");

        pc2kart8.setText("p1k8");

        kullanici1kart1.setText("k1k1");
        kullanici1kart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart1MouseClicked(evt);
            }
        });

        kullanici1kart2.setText("k1k2");
        kullanici1kart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart2MouseClicked(evt);
            }
        });

        kullanici1kart3.setText("k1k3");
        kullanici1kart3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart3MouseClicked(evt);
            }
        });

        kullanici1kart4.setText("k1k4");
        kullanici1kart4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart4MouseClicked(evt);
            }
        });

        kullanici1kart5.setText("k1k5");
        kullanici1kart5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart5MouseClicked(evt);
            }
        });

        kullanici1kart6.setText("k1k6");
        kullanici1kart6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart6MouseClicked(evt);
            }
        });

        kullanici1kart7.setText("k1k7");
        kullanici1kart7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart7MouseClicked(evt);
            }
        });

        kullanici1kart8.setText("k1k8");
        kullanici1kart8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici1kart8MouseClicked(evt);
            }
        });

        pc2kart1.setText("p1k1");

        ortakart1.setText("ortakart");

        kartlariAc.setText("Bilgisayar Kartını Aç");
        kartlariAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartlariAcActionPerformed(evt);
            }
        });

        kartAc.setText("kart aç");
        kartAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartAcActionPerformed(evt);
            }
        });

        kartlarıAco.setText("Oyuncu Kartını Aç");
        kartlarıAco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartlarıAcoActionPerformed(evt);
            }
        });

        ortakart2.setText("ortakart");

        kartAt.setText("KartAt");
        kartAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartAtActionPerformed(evt);
            }
        });

        oyuncupuan.setText("oyuncu puan:");

        bilgisayarpuan.setText("bilgisayar puan:");

        karsilastirmatur.setText("karsılaştırma tür:");

        deste.setText("destee:");
        deste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullanici1kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(422, 422, 422)
                        .addComponent(kullanici1kart4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kullanici1kart5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kullanici1kart6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kullanici1kart7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kullanici1kart8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(kullanici1kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(kullanici1kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(494, 494, 494))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pc2kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc2kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pc2kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pc2kart4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc2kart5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(karsilastirmatur)
                                    .addComponent(oyuncupuan)
                                    .addComponent(bilgisayarpuan))
                                .addGap(141, 141, 141)
                                .addComponent(ortakart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ortakart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deste)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pc2kart6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pc2kart7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pc2kart8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kartAc)
                                    .addComponent(kartlarıAco)
                                    .addComponent(kartAt)
                                    .addComponent(kartlariAc))))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanici1kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kartlarıAco)
                .addGap(18, 18, 18)
                .addComponent(kartAc)
                .addGap(18, 18, 18)
                .addComponent(kartAt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(karsilastirmatur)
                        .addGap(18, 18, 18)
                        .addComponent(oyuncupuan)
                        .addGap(18, 18, 18)
                        .addComponent(bilgisayarpuan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deste)
                            .addComponent(kartlariAc))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pc2kart8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc2kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(1246, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ortakart1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ortakart2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 0, 2000, 1970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanici1kart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart1MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart1.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 0;
                ortakart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = true;
            sayac = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Basketbolcu seciniz");
        }
        sayac1 = 0;
    }//GEN-LAST:event_kullanici1kart1MouseClicked

    private void kullanici1kart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart2MouseClicked
        sonkart++;
        if (sayac == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart2.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 1;
                ortakart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = true;
            sayac = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Basketbolcu seciniz");
        }
        sayac1 = 0;
    }//GEN-LAST:event_kullanici1kart2MouseClicked

    private void kullanici1kart3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart3MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart3.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 2;
                ortakart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = true;
            sayac = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Basketbolcu seciniz");
        }
        sayac1 = 0;
    }//GEN-LAST:event_kullanici1kart3MouseClicked

    private void kullanici1kart4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart4MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart4.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 3;
                ortakart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = true;
            sayac = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Basketbolcu seciniz");
        }
        sayac1 = 0;
    }//GEN-LAST:event_kullanici1kart4MouseClicked

    private void kullanici1kart5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart5MouseClicked
        sonkart++;
        if (sayac1 == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart5.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 0;
                ortakart2.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = false;

            sayac1 = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Futbolcu seciniz");
        }
        sayac = 0;
    }//GEN-LAST:event_kullanici1kart5MouseClicked

    private void kullanici1kart6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart6MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac1 == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart6.setIcon(o.oyuncuImagesf.get(8));

                kullaniciSectigiKart = 1;
                ortakart2.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = false;
            sayac1 = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Futbolcu seciniz");
        }
        sayac = 0;
    }//GEN-LAST:event_kullanici1kart6MouseClicked

    private void kullanici1kart7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart7MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac1 == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart7.setIcon(o.oyuncuImagesf.get(8));

                kullaniciSectigiKart = 2;
                ortakart2.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = false;
            sayac1 = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Futbolcu seciniz");
        }
        sayac = 0;
    }//GEN-LAST:event_kullanici1kart7MouseClicked

    private void kullanici1kart8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici1kart8MouseClicked
        // TODO add your handling code here:
        sonkart++;
        if (sayac1 == 0) {
            if ((String.valueOf(kullanicio.getClass()).equals("class kartoyunu.kullanici"))) {
                kullanici1kart8.setIcon(o.oyuncuImagesf.get(8));
                kullaniciSectigiKart = 3;
                ortakart2.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                ortakart2.setIcon(o.oyuncuImagesf.get(8));
            }
            kartsecimi = false;
            sayac1 = 1;
        } else {
            JOptionPane.showMessageDialog(null, "Futbolcu seciniz");
        }
        sayac = 0;
    }//GEN-LAST:event_kullanici1kart8MouseClicked

    private void kartlariAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartlariAcActionPerformed
        pc2kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[0][0])));
        pc2kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[1][0])));
        pc2kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[2][0])));
        pc2kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[3][0])));
        pc2kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[0][0])));
        pc2kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[1][0])));
        pc2kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[2][0])));
        pc2kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[3][0])));


    }//GEN-LAST:event_kartlariAcActionPerformed
int sonuclandir=0;
    private void kartAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartAcActionPerformed

        Random random = new Random();

        int karsilastirmacesitf;
        int karsilastirmacesitb;
        if (kartsecimi == true) {
            ortakart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
            ortakart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));

            karsilastirmacesitf = random.nextInt(4);
            if (karsilastirmacesitf == 1) {
                karsilastirmatur.setText("PENALTI PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][2]) > Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][2])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][2]) < Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][2])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][2]) == Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][2])) {
                  sonuclandir++;
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }
                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            } else if (karsilastirmacesitf == 2) {
                karsilastirmatur.setText("SERBEST ATIŞ PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][3]) > Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][3])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][3]) < Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][3])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][3]) == Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][3])) {
  sonuclandir++;
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }
                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            } else if (karsilastirmacesitf == 3) {
                karsilastirmatur.setText("KK  PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][4]) > Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][4])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][4]) < Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][4])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesifb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesif[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesif[kullaniciSectigiKart][4]) == Integer.parseInt(oyuncu.kartListesifb[bilgisayarSectigiKart][4])) {
  sonuclandir++;
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(bilgisayaro.kartListesifb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[kullaniciSectigiKart][0])));
                    }
                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }

                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            }

        }
        if (kartsecimi == false) {
            ortakart1.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
            ortakart2.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));

            karsilastirmacesitb = random.nextInt(4);
            if (karsilastirmacesitb == 1) {
                karsilastirmatur.setText("İKİLİK PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][2]) > Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][2])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][2]) < Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][2])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";

                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][2]) == Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][2])) {
  sonuclandir++;
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }
                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            } else if (karsilastirmacesitb == 2) {
                karsilastirmatur.setText("ÜÇLÜK PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][3]) > Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][3])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][3]) < Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][3])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][3]) == Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][3])) {
  sonuclandir++;
                    System.out.println("bill" + bilgisayaro.kartListesibb[bilgisayarSectigiKart][0]);
                    System.out.println("kull " + kullanicio.kartListesib[kullaniciSectigiKart][0]);
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }
                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            } else if (karsilastirmacesitb == 3) {
                karsilastirmatur.setText("SERBEST ATIŞ  PUANLARI");
                if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][4]) > Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][4])) {
                    kullanicio.setSkor(kullanicio.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][4]) < Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][4])) {
                    bilgisayaro.setSkor(bilgisayaro.getSkor() + 10);
                    bilgisayaro.kartListesibb[bilgisayarSectigiKart][0] = "13";
                    kullanicio.kartListesib[kullaniciSectigiKart][0] = "13";
                } else if (Integer.parseInt(oyuncu.kartListesib[kullaniciSectigiKart][4]) == Integer.parseInt(oyuncu.kartListesibb[bilgisayarSectigiKart][4])) {
  sonuclandir++;
                    ortakart1.setIcon(o.oyuncuImagesf.get(8));
                    ortakart2.setIcon(o.oyuncuImagesf.get(8));
                    if (bilgisayarSectigiKart == 0) {
                        pc2kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 1) {
                        pc2kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 2) {
                        pc2kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (bilgisayarSectigiKart == 3) {
                        pc2kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(bilgisayaro.kartListesibb[bilgisayarSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 0) {
                        kullanici1kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 1) {
                        kullanici1kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 2) {
                        kullanici1kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }
                    if (kullaniciSectigiKart == 3) {
                        kullanici1kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[kullaniciSectigiKart][0])));
                    }

                    bilgisayaro.setSkor(bilgisayaro.getSkor());
                    kullanicio.setSkor(kullanicio.getSkor());
                }
                oyuncupuan.setText("Kullanıcı Puan:  " + kullanicio.getSkor());
                bilgisayarpuan.setText("Bilgisayar Puan:  " + bilgisayaro.getSkor());
            }

        }
        if (bilgisayaro.getSkor() + kullanicio.getSkor() == 80) {

            if (bilgisayaro.getSkor() > kullanicio.getSkor()) {

                JOptionPane.showMessageDialog(null, "Tebrikler! Kazanan BİLGİSAYAR");

            } else if (bilgisayaro.getSkor() < kullanicio.getSkor()) {

                JOptionPane.showMessageDialog(null, "Tebrikler! Kazanan KULLANICI");

            } else {
                JOptionPane.showMessageDialog(null, "Oyun Berabere");
            }

        }

    }//GEN-LAST:event_kartAcActionPerformed

    private void kartlarıAcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartlarıAcoActionPerformed
        kullanici1kart1.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[0][0])));
        kullanici1kart2.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[1][0])));
        kullanici1kart3.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[2][0])));
        kullanici1kart4.setIcon(o.oyuncuImagesf.get(Integer.parseInt(kullanicio.kartListesif[3][0])));
        kullanici1kart5.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[0][0])));
        kullanici1kart6.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[1][0])));
        kullanici1kart7.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[2][0])));
        kullanici1kart8.setIcon(o.oyuncuImagesb.get(Integer.parseInt(kullanicio.kartListesib[3][0])));

    }//GEN-LAST:event_kartlarıAcoActionPerformed

    private void kartAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartAtActionPerformed
        // TODO add your handling code here:

        if (kartsecimi == true) {
            bilgisayarSectigiKart = bilgisayaro.kartSecf(bilgisayaro);
            if (bilgisayarSectigiKart == 0) {
                pc2kart1.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 1) {
                pc2kart2.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 2) {
                pc2kart3.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 3) {
                pc2kart4.setIcon(o.oyuncuImagesf.get(8));
            }

            ortakart1.setIcon(o.oyuncuImagesf.get(8));
            ortakart2.setIcon(o.oyuncuImagesf.get(8));

        }

        if (kartsecimi == false) {
            bilgisayarSectigiKart = bilgisayaro.kartSecb(bilgisayaro);
            if (bilgisayarSectigiKart == 0) {
                pc2kart5.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 1) {
                pc2kart6.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 2) {
                pc2kart7.setIcon(o.oyuncuImagesf.get(8));
            } else if (bilgisayarSectigiKart == 3) {
                pc2kart8.setIcon(o.oyuncuImagesf.get(8));
            }
            ortakart1.setIcon(o.oyuncuImagesf.get(8));
            ortakart2.setIcon(o.oyuncuImagesf.get(8));

        }

    }//GEN-LAST:event_kartAtActionPerformed

    private void desteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desteMouseClicked
        kullanici1kart1.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart2.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart3.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart4.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart5.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart6.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart7.setIcon(o.oyuncuImagesf.get(8));
        kullanici1kart8.setIcon(o.oyuncuImagesf.get(8));
        pc2kart1.setIcon(o.oyuncuImagesf.get(8));
        pc2kart2.setIcon(o.oyuncuImagesf.get(8));
        pc2kart3.setIcon(o.oyuncuImagesf.get(8));
        pc2kart4.setIcon(o.oyuncuImagesf.get(8));
        pc2kart5.setIcon(o.oyuncuImagesf.get(8));
        pc2kart6.setIcon(o.oyuncuImagesf.get(8));
        pc2kart7.setIcon(o.oyuncuImagesf.get(8));
        pc2kart8.setIcon(o.oyuncuImagesf.get(8));
    }//GEN-LAST:event_desteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyuncukartlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyuncukartlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyuncukartlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyuncukartlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyuncukartlari().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bilgisayarpuan;
    private javax.swing.JLabel deste;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel karsilastirmatur;
    private javax.swing.JButton kartAc;
    private javax.swing.JButton kartAt;
    private javax.swing.JButton kartlariAc;
    private javax.swing.JButton kartlarıAco;
    private javax.swing.JLabel kullanici1kart1;
    private javax.swing.JLabel kullanici1kart2;
    private javax.swing.JLabel kullanici1kart3;
    private javax.swing.JLabel kullanici1kart4;
    private javax.swing.JLabel kullanici1kart5;
    private javax.swing.JLabel kullanici1kart6;
    private javax.swing.JLabel kullanici1kart7;
    private javax.swing.JLabel kullanici1kart8;
    private javax.swing.JLabel ortakart1;
    private javax.swing.JLabel ortakart2;
    private javax.swing.JLabel oyuncupuan;
    private javax.swing.JLabel pc2kart1;
    private javax.swing.JLabel pc2kart2;
    private javax.swing.JLabel pc2kart3;
    private javax.swing.JLabel pc2kart4;
    private javax.swing.JLabel pc2kart5;
    private javax.swing.JLabel pc2kart6;
    private javax.swing.JLabel pc2kart7;
    private javax.swing.JLabel pc2kart8;
    // End of variables declaration//GEN-END:variables
}
